name: Say Hello Workflow Tiger Tiger Tiger
run-name: commit msg: ${{github.event.head_commit.message}}. Deployed by @${{ github.actor }} - hasH ${{github.sha}}
on: [pull_request_target, issues, push]

jobs:
  greeting-jobs:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
